### ISSUE TITLE
Retrieves All Repositories / Milestones / Issues

### ISSUE THREAD

**Issue by leostera** [ostera/projector#2]
It should:
- [ ] ~~sync automatically on login~~
- [ ] ~~save data in browser~~
- [x] sort data by activity
